/* Import of the main stylesheet generated by the SCSS files */
import '../scss/main.css';

/* This is a very simple component to a display playing instruction and the current letter that is entered. */
export const CurrentGuess = ({guess}) => {

    return (
        <div className={"guess-container"}>
            <h2>Enter a guess by pressing any letter</h2>
            <div className={"guess"}>{guess}</div>
        </div>
    )
}