/* Import of the main stylesheet generated by the SCSS files */
import '../scss/main.css';

/* This is the start/reset button that takes onStartResetGame as a prop from App.js and triggers the onStartResetGame
* function in App.js that resets the state variables and triggers a new random word */
export const StartResetButton = ({onStartResetGame}) => {

    return (
        <div className={"reset-game"}>
            <button
                className={"play-button reset-button"}
                type={"button"}
                /* The pointer to the onStartResetGame function in App.js */
                onClick={onStartResetGame}
            >Start / Reset Game
            </button>
        </div>
    )
}
