/* Import of main stylesheet generated by SCSS files */
import '../scss/main.css';

/* Import of react-module needed in this component */
import { useEffect } from 'react';

/* This component is used to render a message once the user guesses the word correctly or when the hangman figure
* is complete and the user loses. */
export const WinOrLoseMessage = ({correctGuesses, incorrectGuesses, randomWord, setGameIsActive}) => {

    let winOrLoseMessage = '';
    let correctWord = '';
    let gameStillActive = true;

    /* A function to generate a win or lose message based on the correctGuesses and incorrectGuesses arrays as well as
       the actual random word that was generated in App.js  */
    const checkWinOrLose = (correctGuesses, incorrectGuesses, randomWord) => {
        let winOrLose = 'win';

        randomWord.split('').forEach((letter) => {
            if (!correctGuesses.includes(letter)) {
                winOrLose = '';
            }
        })

        if (incorrectGuesses.length === 10) {
            winOrLose = 'lose';
        }

        return winOrLose;

    }

    /* Allocating a message based on the return value of the checkWinOrLose function above and sets game status as
    * no longer active */
    if (checkWinOrLose(correctGuesses, incorrectGuesses, randomWord) === 'win') {
        winOrLoseMessage = "Congratulations! You have won!👑"
        gameStillActive = false;
    } else if (checkWinOrLose(correctGuesses, incorrectGuesses, randomWord) === 'lose') {
        winOrLoseMessage = "Oh no! You lost. 😥"
        correctWord = `The correct word was ${randomWord}`;
        gameStillActive = false;
    }

    /* Using the useEffect hook to update the value of the state variable isGameActive in App.js */
    useEffect(() => setGameIsActive(gameStillActive));

    /* Finally rendering the relevant message */
    return (
        <div className={"win-or-lose-wrapper"}>
            <h2 className={"win-lose-message"}>{winOrLoseMessage}</h2>
            <h3 className={"correct-word"}>{correctWord}</h3>
        </div>
    )
}